### ISSUE TITLE
Errors when running the script

### ISSUE THREAD

**Issue by christianseel** [protonet/letsencrypt#2]
I'm struggling with getting the script running… this is the first error I got:
````
FINISHED --2016-05-27 21:49:56--
Total wall clock time: 24s
Downloaded: 22 files, 73M in 22s (3.39 MB/s)
dpkg: error: requested operation requires superuser privilege
```

I fixed that by changing `dpkg -i *.deb` to `sudo dpkg -i *.deb`.


The next error seems to be related to a missing packages (which is installed before?):
```
Reading package lists... Done
No LSB modules are available.
No LSB modules are available.
To use the Apache Certbot plugin, augeas needs to be installed from precise-backports.
Reading package lists... Done
E: The value 'precise-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

I wasn't able to resolve this. Any hints?

I'm running this on a Carlita with the latest SOUL version stable/89.

**Comment by tiff** [comment]
Wait till soul 2.14.1 - it includes a new letsencrypt script. :)
Am 27.05.2016 9:54 nachm. schrieb "Christian Seel" <notifications@github.com
>:

I'm struggling with getting the script running… this is the first error I
got:

FINISHED --2016-05-27 21:49:56--
Total wall clock time: 24s
Downloaded: 22 files, 73M in 22s (3.39 MB/s)
dpkg: error: requested operation requires superuser privilege

I fixed that by changing dpkg -i *.deb to sudo dpkg -i *.deb.

The next error seems to be related to a missing packages (which is
installed before?):

Reading package lists... Done
No LSB modules are available.
No LSB modules are available.
To use the Apache Certbot plugin, augeas needs to be installed from
precise-backports.
Reading package lists... Done
E: The value 'precise-backports' is invalid for APT::Default-Release
as such a release is not available in the sources

I wasn't able to resolve this. Any hints?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/protonet/letsencrypt/issues/2>, or mute the thread
<https://github.com/notifications/unsubscribe/AACR8xCJWzgNM_jjBa83jvj4-HeREN41ks5qF0vogaJpZM4Io0QU>
.

**Comment by tiff** [comment]
stable/90 will be released next week. it contains a script that generates a valid certificate for the custom nodename and adds a cronjob that's updating the certificate once a month.
